"""Amadeus runtime context and prompt assembly package."""

from amadeus.context import (
    ContextFrameResult,
    ContextBuilder,
    ContextRenderResult,
    Message,
    MessageEnvelopeBuilder,
    PromptDebugEntry,
    RuntimeContext,
    SystemPromptBuilder,
    SystemPromptResult,
)
from amadeus.bootstrap import (
    PassiveApp,
    RuntimeConfig,
    build_passive_app,
    default_workspace_root,
    load_runtime_config,
)
from amadeus.events import EventBus, TurnCommitted
from amadeus.memory import (
    ConsolidateRequest,
    ConsolidateResult,
    MarkdownMemoryMaintenance,
    MarkdownMemoryRuntime,
    MarkdownMemoryStore,
    MemoryOptimizer,
    MemoryOptimizerBusy,
    RefreshRecentTurnsRequest,
    build_markdown_memory_runtime,
)
from amadeus.memory_engine import (
    EvidenceRef,
    MemoryEngine,
    MemoryIngestRequest,
    MemoryIngestResult,
    MemoryQuery,
    MemoryQueryResult,
    MemoryRecord,
)
from amadeus.prompting import (
    DEFAULT_CONTEXT_TRIM_PLANS,
    PromptAssembler,
    PromptAssemblyResult,
    PromptSectionRender,
    build_context_trim_attempts,
)
from amadeus.provider import (
    ContentSafetyError,
    ContextLengthError,
    LLMProvider,
    LLMProviderConfig,
    LLMResponse,
)
from amadeus.response_parser import ParsedResponse, ResponseMetadata, parse_response
from amadeus.runtime import PassiveRuntime, PassiveTurnResult
from amadeus.session import (
    Session,
    SessionManager,
    SessionStore,
    fetch_messages,
    search_messages,
)
from amadeus.prompt_block import (
    ActiveSkillsPromptBlock,
    BehaviorRulesPromptBlock,
    IdentityPromptBlock,
    LongTermMemoryPromptBlock,
    PromptBlock,
    PromptBlockRenderResult,
    RecentContextPromptBlock,
    RetrievedMemoryPromptBlock,
    RuntimeMetadataPromptBlock,
    SelfModelPromptBlock,
)
from amadeus.workspace import DEFAULT_SELF_MD, initialize_workspace

__all__ = [
    "ActiveSkillsPromptBlock",
    "BehaviorRulesPromptBlock",
    "ContextFrameResult",
    "ContextBuilder",
    "ContextRenderResult",
    "ConsolidateRequest",
    "ConsolidateResult",
    "ContentSafetyError",
    "DEFAULT_SELF_MD",
    "DEFAULT_CONTEXT_TRIM_PLANS",
    "EventBus",
    "EvidenceRef",
    "IdentityPromptBlock",
    "LLMProvider",
    "LLMProviderConfig",
    "LLMResponse",
    "LongTermMemoryPromptBlock",
    "MarkdownMemoryMaintenance",
    "MarkdownMemoryRuntime",
    "MarkdownMemoryStore",
    "Message",
    "MessageEnvelopeBuilder",
    "MemoryOptimizer",
    "MemoryOptimizerBusy",
    "MemoryEngine",
    "MemoryIngestRequest",
    "MemoryIngestResult",
    "MemoryQuery",
    "MemoryQueryResult",
    "MemoryRecord",
    "PassiveRuntime",
    "PassiveTurnResult",
    "PassiveApp",
    "ParsedResponse",
    "PromptBlock",
    "PromptBlockRenderResult",
    "PromptAssembler",
    "PromptAssemblyResult",
    "PromptDebugEntry",
    "PromptSectionRender",
    "RecentContextPromptBlock",
    "RetrievedMemoryPromptBlock",
    "RuntimeContext",
    "RuntimeConfig",
    "RuntimeMetadataPromptBlock",
    "RefreshRecentTurnsRequest",
    "ResponseMetadata",
    "Session",
    "SessionManager",
    "SessionStore",
    "SelfModelPromptBlock",
    "SystemPromptBuilder",
    "SystemPromptResult",
    "TurnCommitted",
    "build_markdown_memory_runtime",
    "build_passive_app",
    "build_context_trim_attempts",
    "default_workspace_root",
    "fetch_messages",
    "initialize_workspace",
    "load_runtime_config",
    "parse_response",
    "search_messages",
]
